version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - 5432:5432

  spring-app:
    build:
      context: ./my-spring-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres